version: '3'
services:
  scraper:
    build: ./scraper
    container_name: Doctorise_scraper_container
    volumes:
      - ./db:/app/db  # Mount the db folder from host to container
    networks:
      - project_network
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_CHANNEL_IDS=${TELEGRAM_CHANNEL_IDS}
      - DB_FILE=/app/db/jobs.db  # Path to the SQLite DB inside the container
    restart: unless-stopped  # Ensures container restarts if it crashes

networks:
  project_network:
    driver: bridge
